---
- name: "DELETE File_listed"
  file:
    path: ./lists/listed.csv
    state: absent

- name: merge
  shell: |
    echo "HostName, Management-IP, CPU Core, Sockets, Memory Capacity," >>  ./lists/listed.csv 
    cat ./lists/*.dat >> ./lists/listed.csv ¥
    rm -rf ./lists/*.dat
