- name: Append Disk Task
  vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    name: '{{ inventory_hostname }}'
    disk: '{{ append_disk }}'
  delegate_to: localhost
  register: disk_facts