- name: Append Disk Task
  when: item.Disk.size_gb != "none"
  vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    name: '{{ inventory_hostname }}'
    disk: 
      - size_gb:          '{{ item.Disk.size_gb }}'
        type:             '{{ item.Disk.type }}'
        datastore:        '{{ item.Disk.datastore }}'
        state:            '{{ item.Disk.state }}'
        scsi_controller:  '{{ item.Disk.scsi_controller }}'
        unit_number:      '{{ item.Disk.unit_number }}'
        scsi_type:        'paravirtual'
  delegate_to: localhost
  with_items:
    - '{{ Partition }}'