---
- set_fact:
    Network: "{{ BaseNetwork + AppendNetwork }}"

- name: "Remove ALL Route"
  win_command: powershell.exe -
  args:
    stdin: Remove-NetRoute  -DestinationPrefix 0.0.0.0/0 -confirm:$false

- name: "[netsh] Set IP configure"
  win_command: powershell.exe -
  args:
    stdin: netsh interface ip set address "{{ item.names.nic_name }}" static {{ item.interface.ip }} {{ item.interface.netmask }} {{ item.interface.gateway }}
  with_items:
    - "{{ Network }}"

- name: Wait for 10min
  wait_for_connection:
    delay: 5
    timeout: 600

- name: "[DNS] Set DNS Address"
  win_dns_client:
    adapter_names:  '{{ item.names.nic_name }}'
    ipv4_addresses: 
      - '{{ item.dnslist.dns1 }}'
      - '{{ item.dnslist.dns2 }}'
  with_items:
    - '{{ Network }}'
  ignore_errors: yes


