---
- name: Create vm folders on given datacenter
  vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter }}'
    folder_name: '{{ item.name }}'
    folder_type: '{{ item.type }}'
    state: '{{ item.state }}'
    validate_certs: no
  delegate_to: localhost
  with_items:
    - '{{ Folders }}'
    



