---
- name: Create datastore cluster
  vmware_datastore_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter }}'
    datastore_cluster_name: '{{ datastore }}'
    state: present
    validate_certs: no
  delegate_to: localhost