---
- name: Create Cluster
  vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter }}'
    cluster_name: '{{ cluster }}'
    enable_ha: no
    enable_drs: yes
    enable_vsan: yes
    validate_certs: no
    vsan_auto_claim_storage: yes
  delegate_to: localhost