---
- name: reConfigure Interface 
  vmware_guest:
    # Configure Target
    state:                    'present'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    datacenter:               '{{ datacenter }}'
    datastore:                '{{ datastore }}'
    cluster:                  '{{ cluster }}'

    name:                     '{{ inventory_hostname }}'

    networks: '{{ export_nic }}'
      # - name:                 '{{ item.interface.name }}'
      #   dvswitch_name:        '{{ item.interface.name }}'
      #   device_type:          '{{ item.interface.name }}'
      #   ip:                   '{{ item.interface.name }}'
      #   netmask:              '{{ item.interface.name }}'
      #   gateway:              '{{ item.interface.name }}'
      #   start_connected:      true

  delegate_to: localhost
  # with_items:
  #   - '{{ Network }}'

