- hosts: vcsa
  connection: local
  gather_facts: no
  roles:
   # - vCenter-License
    - vCenter-Datacenter
    - vCenter-Cluster


# - hosts: vsan
#   connection: local
#   gather_facts: no
#   roles:
#     - vSAN-hosts-Configure

- hosts: esxi
  connection: local
  gather_facts: no
  roles:
    - ESXi-add_host

- hosts: vcsa
  connection: local
  gather_facts: no
  roles:
    - vCenter-Portgroup
    - vCenter-ResourcePool
    - vCenter-Folder
    - vCenter-DeployOVA

- hosts: virtualmachine
  connection: local
  gather_facts: no
  roles:
    - vCenter-VirtualMachine
    - vCenter-VirtualMachine
