- hosts: vcsa
  connection: local
  gather_facts: no
  roles:
    - vCenter-Prefix-Configure


- hosts: esxi
  connection: local
  gather_facts: no
  roles:
    - ESXi-hosts-Configure

- hosts: vcsa
  connection: local
  gather_facts: no
  roles:
    - vCenter-Postfix-Configure
