- hosts: vcsa
  connection: local
  gather_facts: no
  roles:
    - vCenter-Prefix-Configure


# - hosts: vsan
#   connection: local
#   gather_facts: no
#   roles:
#     - vSAN-hosts-Configure

- hosts: esxi
  connection: local
  gather_facts: no
  roles:
    - ESXi-hosts-Configure

- hosts: vcsa
  connection: local
  gather_facts: no
  roles:
    - vCenter-Postfix-Configure


- hosts: vmlist
  connection: local
  gather_facts: no
  roles:
    - vCenter-VirtualMachine
