
- hosts: 
    - Storage_Management_Server
    - Virt_Management_Server
  connection: local
  ignore_errors: yes
  gather_facts: no
  roles:
    - vm_deploy_clone
    - vm_custom_nic
    - vm_custom_disk
    - vm_power_on
    - sys_wait_10min





- hosts: 
    - Storage_Management_Server
    - Virt_Management_Server
  gather_facts: yes
  roles:
    - windows_part_resize
    - windows_set_pagefile
    - windows_network_nic


- hosts:
    - Storage_Management_Server
    - Virt_Management_Server
  connection: local
  gather_facts: no
  roles:
    - windows_part_append