- name: Gather some facts from a guest using the vSphere API output schema
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    name: "{{ inventory_hostname }}"
    schema: "vsphere"
    #properties: "guest.net.network"
    properties: "guest.net"
  delegate_to: localhost
  register: result


- name: Get Interface 
  win_command: powershell.exe -
  args:
    stdin: Get-NetAdapter | Select-Object Name,MacAddress
  # with_items: '{{result.instance.guest.net }}'
  # register: mac_to_ipaddress


# - template:
#     src:  machinelist.j2
#     dest: ./{{ inventory_hostname }}.log
#   delegate_to: localhost