- name: Change hostname to inventory_hostname
  win_command: powershell.exe -
  args:
    stdin: Rename-Computer -NewName "{{ inventory_hostname }}" -Force

- name: Set Interface name
  ignore_errors: yes
  win_command: powershell.exe -
  args:
    stdin: Rename-NetAdapter -Name {{ item.names.before }} -NewName {{ item.names.after }}
  with_items:
    - "{{ Network }}"

- name: Set to disable ipv6
  ignore_errors: yes
  win_command: powershell.exe -
  args:
    stdin: Disable-NetAdapterBinding -Name "{{ item.names.after }}" -ComponentID ms_tcpip6
  with_items:
    - "{{ Network }}"
