---
- name: '[ACTION] Change to online for target'
  when: item.Disk.size_gb != 0
  win_command: powershell.exe -
  args:
    stdin: Set-Disk -Number {{ item.Part.unit_number }} -IsOffline $false
  with_items:
    - '{{ Disks }}'
  register: result

- name: '[ACTION] Initialize disk for target'
  when: item.Disk.size_gb != 0
  win_command: powershell.exe -
  args:
    stdin: Initialize-Disk -Number {{ item.Part.unit_number }} -PartitionStyle {{ item.Part.partition_style }} -PassThru
  ignore_errors:    yes
  with_items:
    - '{{ Disks }}' 

- name: '[ACTION] Create partition for target'
  when: item.Disk.size_gb != 0
  win_partition:
    drive_letter:   '{{ item.Part.letter }}'
    partition_size: '{{ item.Part.partition_size }}'
    disk_number:    '{{ item.Part.unit_number }}'
    state:          present
    offline:        no
    read_only:      no
  ignore_errors:    yes
  with_items:
    - '{{ Disks }}' 

- name: '[ACTION] Format partition for target'
  when: item.Disk.size_gb != 0
  win_format:
    drive_letter: '{{ item.Part.letter }}'
    file_system:  '{{ item.Part.fs_type }}'
    new_label:    ''
    full:         false
  with_items:
    - '{{ Disks }}' 