---
- name: Clone a virtual machine from Windows template and customize
  vmware_guest:
    # Configure Target
    state:                    'present'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    datacenter:               '{{ datacenter }}'
    datastore:                '{{ datastore }}'
    cluster:                  '{{ cluster }}'
    folder: /


    # Configure Virtual Machine over view
    name:                     '{{ inventory_hostname }}'

    template:                 '{{ template }}'
    networks:
    - name:                   '{{ port_group }}'
      device_type:            '{{ device_type }}'
      ip:                     '{{ ansible_host }}'
      netmask:                '{{ netmask }}'
      gateway:                '{{ gateway }}'
      domain:                 '{{ domain_name }}'
      start_connected:        true
      dns_servers:
      - 10.52.1.50
      - 10.52.1.51

    customization:
      # productid:            ''
      autologon:              True
      autologoncount:         1
      ## Login customize ##
      fullname:               '{{ ansible_user }}'
      password:               '{{ ansible_password }}'
      ## Set domain infomation ##
      # domain_admin:         ''
      # domainadminpassword:  ''
      # dns_servers:
      # - 192.168.1.100
      domain: '{{ domain_name }}'
      runonce:
        - netsh advfirewall set allprofiles state off
        - powershell.exe -ExecutionPolicy RemoteSigned -Command "winrm qc -Force "
        - powershell.exe -ExecutionPolicy RemoteSigned -Command "Enable-PSRemoting -force" 
        - powershell.exe -ExecutionPolicy RemoteSigned -Command "Set-ExecutionPolicy RemoteSigned -Force" 
        - reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\PoliciesSystem /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 1 /f 
        - winrm set winrm/config/service/auth @{Basic="true"}
        - winrm set winrm/config/service @{AllowUnencrypted="true"}
  delegate_to: localhost