---
- name: Fix time
  win_command: powershell.exe -
  args:
    stdin: Set-Date "2019/11/14 17:10:00"

- name: get date
  run_once: yes 
  win_command: powershell.exe -
  args:
    stdin: Get-Date -Uformat %Y%m%d
  register: date

# - name: '[Hinemos] Uninstall Service'
#   win_command: powershell.exe - 
#   args:
#     stdin: Start-Process 'C:\Program Files (x86)\Hinemos\Agent6.2.2\bin\HinemosAgentService64.exe' '-uninstall Hinemos_6.2_Agent'

# - win_reboot:

# - name: '[Hinemos] Install Service'
#   win_command: powershell.exe -
#   args:
#     stdin: Start-Process 'C:\Program Files (x86)\Hinemos\Agent6.2.2\bin\RegistAgentService.bat'

# - name: '[VBCorp] Install Service'
#   win_shell: C:\JBS_work\VBCorp\q20_Connect_hq_sat_0200_20191106_64bit.exe

# - pause:
#     second: 300

# - win_reboot:

- name: Copy File
  win_copy:
    src: '{{ item }}'
    dest: C:\JBS_work\
  with_items:
    - Parameter_Check.bat
    - Parameter_Check.ps1

- name: 'Get Facts'
  win_shell: C:\JBS_work\Parameter_Check.bat

- name: '[Fetch] Parameta' 
  win_command: powershell.exe -
  args:
    stdin: Get-Content C:\JBS_work\{{ inventory_hostname }}_{{ datenum }}_Paramater_Check.txt
  vars: 
    datenum: "{{ date.stdout|regex_replace ('\\r','')|regex_replace ('\\n','') }}"
  register: result

- name: '[SAVE] Paramata'
  template:
    src: result.j2
    dest: ./log/{{ inventory_hostname }}_{{ datenum }}_Paramater_Check.txt
  vars: 
    datenum: "{{ date.stdout|regex_replace ('\\r','')|regex_replace ('\\n','') }}"
    context: "{{ result.stdout }}"
  delegate_to: localhost


