---
- name: Change hostname to inventory_hostname
  win_command: powershell.exe -
  args:
    stdin: if( $ENV:COMPUTERNAME -ne "{{ inventory_hostname }}" ){Rename-Computer -NewName "{{ inventory_hostname }}" -Force; echo "Hostname Changed"}else{ echo "Hostname not Changed" }
  ignore_errors: yes
  register: result

- debug:
    msg: '{{ change_state }}'
  vars: 
    change_state: '{{ result.stdout_lines }}'

- name: Set Interface name
  ignore_errors: yes
  win_command: powershell.exe -
  args:
    stdin: Get-NetAdapter -InterfaceDescription "{{ item.names.adapter }}" | Rename-NetAdapter -NewName "{{ item.names.nic_name }}"
  with_items:
    - "{{ Network }}"


- name: Set to all interface ipv6 disable
  ignore_errors: yes
  win_command: powershell.exe -
  args:
    stdin: Get-NetAdapter -InterfaceDescription "{{ item.names.adapter }}" | Disable-NetAdapterBinding  -ComponentID ms_tcpip6
  with_items:
    - "{{ Network }}"


- name: Disable IPv6 components
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisableComponents
    type: dword
    data: 0xff

- name: "[DNS] Set DNS Address in Operation"
  win_dns_client:
    adapter_names: Operation
    ipv4_addresses: 
      - 10.40.3.120

- name: "[Gateway] Set Default Gateway"
  win_command: powershell.exe -
  args:
    stdin: Get-NetAdapter -InterfaceDescription "{{ Network[0].names.adapter }}" | Remove-NetRoute -DestinationPrefix 0.0.0.0/0 -confirm:$false; Get-NetAdapter -InterfaceDescription "{{ Network[0].names.adapter }}" | Remove-NetIPAddress -confirm:$false; Get-NetAdapter -InterfaceDescription "{{ Network[0].names.adapter }}" | New-NetIPAddress -AddressFamily IPv4 -IPAddress '{{ ansible_host }}' -prefix 25 -DefaultGateway 10.40.3.120
  ignore_errors: yes
  async: 15
  poll: 15



- name: Enable SMB MultiChannel Server setting
  win_command: powershell.exe -
  args:
    stdin: Set-SmbServerConfiguration -EnableMultiChannel $true -Force

- name: Enable SMB MultiChannel Client setting
  win_command: powershell.exe -
  args:
    stdin: Set-SmbClientConfiguration -EnableMultiChannel $true -Force