---
- name: '[ACTION:VirtualMemory] Set pagefile size'
  win_pagefile:
    drive: C
    remove_all: true
- win_pagefile:
    drive: C
    initial_size: 32768
    maximum_size: 32768
    state: present


- name: '[ACTION:RAM_Dump] Set to Auto(7)'
  changed_when: '"successful." in result.stdout'
  win_command: powershell.exe -
  args:
    stdin: wmic RECOVEROS set DebugInfoType=7
  register: result


- name: '[ACTION:WindowsFeatuer] Setup Windows Feature'
  when: '"" != item'
  win_feature:
    name:   "{{ item }}"
    state:  present
  with_items:
    - "{{ windows_feature_set }}"