---
- name: "Windows Feature"
  win_feature:
    name:   "{{ item }}"
    state:  present
  with_items:
    - "{{ windows_feature_set }}"

# - name: Install NET-Framework-Core from file
#   win_feature:
#     name: NET-Framework-Core
#     source: X:\sources\sxs
#     state: present

# - name: Facts Feature
#   win_command: powershell.exe -
#   args:
#     stdin: Get-WindowsFeature
#   register: result

# - name: Out File
#   delegate_to: localhost
#   copy:
#     content: "{{ report }}"
#     dest: "{{ inventory_dir }}/Logs/{{ inventory_hostname }}/WinFeature.log "
#   vars: 
#     report: "{{ result.stdout }}"