---
- name: Clone a virtual machine from Windows template and customize
  vmware_guest:
    # Configure Target
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    datacenter:               '{{ datacenter }}'
    datastore:                '{{ datastore }}'
    cluster:                  '{{ cluster }}'
    folder: /

    # Configure Virtual Machine over view
    name:                     '{{ inventory_hostname }}'
    template:                 '{{ template }}'
    hardware:
      memory_mb:              '{{ memory_mb }}'
      nested_virt:            '{{ hvOn }}'
      num_cpus:               '{{ num_cpus }}'
      boot_firmware:          '{{ bootfirm }}'
    networks:
    - name:                   'Default'
      device_type:            '{{ device_type }}'
      ip:                     '{{ ansible_host }}'
      netmask:                '{{ netmask }}'
      gateway:                '{{ gateway }}'
      # mac:
      domain:                 '{{ domain_name }}'
      dns_servers:
      - 192.168.1.100
      start_connected: yes
      #- vlan: 0
      #type: dhcp

    customization:
      # productid:            ''
      autologon:              False
      ## Login customize ##
      fullname:               '{{ userename }}'
      password:               '{{ password }}'
      ## Set domain infomation ##
      # domain_admin:         ''
      # domainadminpassword:  ''
      dns_servers:
      - 192.168.1.100
      domain: '{{ domain_name }}'
      # runonce:
      #  - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  delegate_to: localhost

