---
- name: Delete Default Gateway
  win_command: powershell.exe -
  args:
    stdin: Start-Job { Get-NetAdapter -Name '{{ Network[1].names.after }}' | Remove-NetRoute -DestinationPrefix 0.0.0.0/0 -confirm:$false; Get-NetAdapter -Name "Operation" | Remove-NetIPAddress -confirm:$false; Get-NetAdapter -Name '{{ Network[1].names.after }}' | New-NetIPAddress -AddressFamily IPv4 -IPAddress '{{ ansible_host }}' -prefix 25 -DefaultGateway 10.40.3.120 -confirm:$false }
  ignore_errors: yes

- name: Wait for 10min
  wait_for_connection:
    delay: 30
    timeout: 600