---
- name: machine poweroff (ACPI)
  vmware_guest_powerstate :
    # Configure Target
    state:                    'shutdown-guest'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    name:                     '{{ inventory_hostname }}'
  delegate_to: localhost

- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20
  delegate_to: localhost
  run_once: yes

- name: destroy virtual machine
  vmware_guest:
    # Configure Target
    state:                    'absent'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    datacenter:               '{{ datacenter }}'
    datastore:                '{{ datastore }}'
    cluster:                  '{{ cluster }}'
    name:                     '{{ inventory_hostname }}'
  delegate_to: localhost    
