---
- name: Set timezone to Tokyo Standard Time
  win_timezone:
    timezone: Tokyo Standard Time
# https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)?redirectedfrom=MSDN
  register: result
