---
- name: Format host_vars
  file:
    path: ./host_vars
    state: "absent"
    mode: 755
    force: true

- name: Initialize host_vars
  file:
    path: ./host_vars
    state: "directory"
    mode: 755
    force: true

- name: Initialize group_vars
  file:
    path: ./host_vars
    state: "directory"
    mode: 755
    force: true

