---
- name: '[ACTION] Deploy VM using Cloning'
  vmware_guest:
  # vCenter Setting
    state:                    '{{ statement }}'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    datacenter:               '{{ datacenter }}'
    datastore:                '{{ datastore }}'
    cluster:                  '{{ cluster }}'
    folder:                   '{{ deploy_folder }}'
  # VM Setting
    name:                     '{{ inventory_hostname }}'
    convert:                  '{{ disk_type }}'
    template:                 '{{ template }}'
    hardware:
      memory_mb:                '{{ memory_mb }}'
      nested_virt:              '{{ hvOn }}'
      num_cpus:                 '{{ num_cpus }}'
      num_cpu_cores_per_socket: '{{ num_cpus }}'
      boot_firmware:            '{{ bootfirm }}'
    disk:
      - size_gb:              '{{ disk_size }}'
        datastore:            '{{ datastore }}'
    networks:                 '{{ export_nic }}'
  # VMware Tools customization
    customization:
      productid:            '{{ license }}'
      autologon:              True
      autologoncount:         1
      fullname:               '{{ ansible_user }}'
      password:               '{{ ansible_password }}'
      # domain_admin:         ''
      # domainadminpassword:  ''
      # dns_servers:
      # - 192.168.1.100
      # domain:               '{{ domain_name }}'
      runonce:
        - netsh advfirewall set allprofiles state off
        - powershell.exe -ExecutionPolicy RemoteSigned -Command "winrm qc -Force "
        - powershell.exe -ExecutionPolicy RemoteSigned -Command "Enable-PSRemoting -Force" 
        - powershell.exe -ExecutionPolicy RemoteSigned -Command "Set-ExecutionPolicy RemoteSigned -Force"
        - reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\PoliciesSystem /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 1 /f 
        - winrm set winrm/config/service/auth @{Basic="true"}
        - winrm set winrm/config/service @{AllowUnencrypted="true"}
  delegate_to: localhost

- name: '[ACTION] Force online Network Adapter'
  vmware_guest:
    state:                    'present'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    datacenter:               '{{ datacenter }}'
    datastore:                '{{ datastore }}'
    cluster:                  '{{ cluster }}'
    folder:                   '{{ deploy_folder }}'
    name:                     '{{ inventory_hostname }}'
    networks:                 '{{ export_nic }}'
  delegate_to: localhost

- name: '[ACTION] Append custom disk'
  when: export_disk[0].size_gb != 0
  vmware_guest_disk:
    hostname:                 "{{ vcenter_hostname }}"
    username:                 "{{ vcenter_username }}"
    password:                 "{{ vcenter_password }}"
    datacenter:               "{{ datacenter }}"
    validate_certs:           no
    name:                     '{{ inventory_hostname }}'
    disk:                     '{{ export_disk }}'
  delegate_to: localhost

- name: '[ACTION] VM Powerd on'
  vmware_guest_powerstate :
    state:                    'powered-on'
    hostname:                 '{{ vcenter_hostname }}'
    username:                 '{{ vcenter_username }}'
    password:                 '{{ vcenter_password }}'
    validate_certs:           'no'
    name:                     '{{ inventory_hostname }}'
  delegate_to: localhost