---
- name: Add ESXi Host to vCenter
  vmware_host:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ datacenter }}'
    cluster_name: '{{ cluster }}'
    #esxi_hostname: '{{ inventory_hostname }}.{{ domain_network }}'
    esxi_hostname: '{{ ansible_host }}'
    esxi_username: '{{ esxi_user }}'
    esxi_password: '{{ esxi_password }}'
    state: present
    validate_certs: no
  delegate_to: localhost
