- name: Configure VSAN
  vmware_vsan_cluster:
    hostname: "{{ ansible_host }}"
    username: '{{ esxi_user }}'
    password: '{{ esxi_password }}'
    validate_certs: no
  delegate_to: localhost
  register: vsan_cluster