---
- set_fact:
    Network: "{{ BaseNetwork + AppendNetwork }}"

- set_fact:
    Overwrite: "{{ OverwriteNetwork + AppendNetwork }}"

- name: '[INIT] Flush Old data'
  file:
    path: '{{ item }}'
    state: "absent"
    force: yes
  with_items:
    - ./host_vars
    - ./group_vars
    - ./log
  delegate_to: localhost
  run_once: yes

- name: '[INIT] Initialize workspace'
  file:
    path:  '{{ item }}'
    state: "directory"
    force: yes
  with_items:
    - ./host_vars
    - ./group_vars
    - ./log
  delegate_to: localhost
  run_once: yes

- name: '[EXPORT] Interface vars'
  template:
    src:  host_vars.j2
    dest: ./host_vars/{{ inventory_hostname }}.yml
  delegate_to: localhost





